/*
================================================================================
Magnitude Exploration
================================================================================

Script Purpose:
    This script explores the magnitude of different measures in the data warehouse.
    It performs the following checks:
    - Finds total customers by country and by gender.
    - Finds total products by category.
    - Calculates average product costs per category.
    - Calculates total revenue per category and per customer.
    - Finds the distribution of sold items across countries.
================================================================================
*/

-- Find total customers by countries
SELECT country,
       COUNT(DISTINCT customer_key) AS total_customers_per_country
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers_per_country;

-- Find total customers by gender
SELECT gender,
       COUNT(DISTINCT customer_key) AS total_customers_per_gender
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers_per_gender;

-- Find total products by category
SELECT category,
       COUNT(DISTINCT product_key) AS total_products_per_category
FROM gold.dim_products
GROUP BY category
ORDER BY total_products_per_category;

-- Find average cost in each category
SELECT category,
       AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost;

-- Find total revenue generated for each category
SELECT pr.category,
       SUM(ft.sales_amount) AS revenue_prod
FROM gold.fact_sales ft
LEFT JOIN gold.dim_products pr
       ON ft.product_key = pr.product_key
GROUP BY pr.category
ORDER BY revenue_prod;

-- Find total revenue generated by each customer
SELECT cu.customer_key,
       cu.firstname,
       cu.lastname,
       SUM(ft.sales_amount) AS revenue_cust
FROM gold.fact_sales ft
LEFT JOIN gold.dim_customers cu
       ON ft.customer_key = cu.customer_key
GROUP BY cu.customer_key, cu.firstname, cu.lastname
ORDER BY revenue_cust;

-- Find distribution of sold items across countries
SELECT cu.country,
       SUM(f.quantity) AS dist_items
FROM gold.fact_sales f
LEFT JOIN gold.dim_customers cu
       ON f.customer_key = cu.customer_key
GROUP BY cu.country
ORDER BY dist_items;
